location ^~ /drupal/ {
  root /var/www/html;
  index index.php index.html;

  # Rewrite the URI so Drupal works from a subdirectory
  rewrite ^/drupal(/.*)$ $1 break;

  try_files $uri /index.php?$query_string;

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root/drupal-backend/web$fastcgi_script_name;
    fastcgi_pass unix:/var/run/php/php-fpm.sock;
  }
}
